### Create note
POST https://k48o8n9ofl.execute-api.us-east-1.amazonaws.com/dev/notes
Content-Type: application/json
Authorization: eyJraWQiOiJrb3RSYU1DRVhBdzhDUENYXC9acE9EcjVnZ3JpXC95ZTlJcnhVNGYzMjl0RDQ9IiwiYWxnIjoiUlMyNTYifQ.eyJvcmlnaW5fanRpIjoiNGZmODFmODgtZjIwYS00M2U3LWIyZDEtODdjODRhYjljYTA4Iiwic3ViIjoiYzRjOTFiMmItMGM4Ni00MGJmLWExZjgtOTI4ZTM0NDdkMjgxIiwiYXVkIjoiNXQwZ2RiaDcycXU1djVsbmdqMGdqZG0zdTUiLCJldmVudF9pZCI6IjgxNTE3YzVlLWRhZDAtNGUyYy1hMWZlLTIwMmFhMmRjOWRhNCIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNjg2MjI2MDMzLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9EVTBvb3lwazIiLCJjb2duaXRvOnVzZXJuYW1lIjoidGVzdCIsImV4cCI6MTY4NjIyOTYzMywiaWF0IjoxNjg2MjI2MDMzLCJqdGkiOiIwZjYxNjk5OC0zYmJmLTQzNmUtOWQ3NS0yY2MwMmU2Y2ZhZjIifQ.A6e1ecQYloCl-pKa8U4k0U1c_vvEp5fTbwIATmumfNxaYlk4rTXV1vgO4yaVxDrY9vhVWndCqhmA8eGxeeKCoHoyVkvYnIUWDsvtI56D80ZRQ6imLKzULlZHG0Yj78oIu_pmOINgHlOM-GzQ4_5qG3QJ_q9OrbHYg6JBn3TOTqkgl6109aTDiskzZY32X8iVyO3MLAujqTPs61yGgfdXiXlDR9oRcROwliz-SHE8OHjQjKFiWK_R1gyp6Gm5_FF2QfxpCP0MadtUVj0nOzA6sUzpdv3MKhZkMOd2Wpa1yot734k0m6OiiV-lNAPkABIXumUjFr5yED0n1yqtRD9Khg

{
    "id": "103",
    "title": "my first note",
    "content": "Hello world!"
}


### Update note
PUT https://k48o8n9ofl.execute-api.us-east-1.amazonaws.com/dev/notes/1003
Content-Type: application/json
Authorization: eyJraWQiOiJrb3RSYU1DRVhBdzhDUENYXC9acE9EcjVnZ3JpXC95ZTlJcnhVNGYzMjl0RDQ9IiwiYWxnIjoiUlMyNTYifQ.eyJvcmlnaW5fanRpIjoiNGZmODFmODgtZjIwYS00M2U3LWIyZDEtODdjODRhYjljYTA4Iiwic3ViIjoiYzRjOTFiMmItMGM4Ni00MGJmLWExZjgtOTI4ZTM0NDdkMjgxIiwiYXVkIjoiNXQwZ2RiaDcycXU1djVsbmdqMGdqZG0zdTUiLCJldmVudF9pZCI6IjgxNTE3YzVlLWRhZDAtNGUyYy1hMWZlLTIwMmFhMmRjOWRhNCIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNjg2MjI2MDMzLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9EVTBvb3lwazIiLCJjb2duaXRvOnVzZXJuYW1lIjoidGVzdCIsImV4cCI6MTY4NjIyOTYzMywiaWF0IjoxNjg2MjI2MDMzLCJqdGkiOiIwZjYxNjk5OC0zYmJmLTQzNmUtOWQ3NS0yY2MwMmU2Y2ZhZjIifQ.A6e1ecQYloCl-pKa8U4k0U1c_vvEp5fTbwIATmumfNxaYlk4rTXV1vgO4yaVxDrY9vhVWndCqhmA8eGxeeKCoHoyVkvYnIUWDsvtI56D80ZRQ6imLKzULlZHG0Yj78oIu_pmOINgHlOM-GzQ4_5qG3QJ_q9OrbHYg6JBn3TOTqkgl6109aTDiskzZY32X8iVyO3MLAujqTPs61yGgfdXiXlDR9oRcROwliz-SHE8OHjQjKFiWK_R1gyp6Gm5_FF2QfxpCP0MadtUVj0nOzA6sUzpdv3MKhZkMOd2Wpa1yot734k0m6OiiV-lNAPkABIXumUjFr5yED0n1yqtRD9Khg

{
    "title": "Update title",
    "content": "Hello again!"
}


### Delete note
DELETE https://k48o8n9ofl.execute-api.us-east-1.amazonaws.com/dev/notes/1003
Authorization: eyJraWQiOiJrb3RSYU1DRVhBdzhDUENYXC9acE9EcjVnZ3JpXC95ZTlJcnhVNGYzMjl0RDQ9IiwiYWxnIjoiUlMyNTYifQ.eyJvcmlnaW5fanRpIjoiOTUzMTViYTctMWIzMy00NjNmLWFlNWYtMzU4NGI1NGI0MDQ2Iiwic3ViIjoiYzRjOTFiMmItMGM4Ni00MGJmLWExZjgtOTI4ZTM0NDdkMjgxIiwiYXVkIjoiNXQwZ2RiaDcycXU1djVsbmdqMGdqZG0zdTUiLCJldmVudF9pZCI6ImI0YTcyNWRjLTZlODktNDdhNS1iNGNmLWY1NzQ0MzVmODg5NSIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNjg2MjIyMjQ4LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9EVTBvb3lwazIiLCJjb2duaXRvOnVzZXJuYW1lIjoidGVzdCIsImV4cCI6MTY4NjIyNTg0OCwiaWF0IjoxNjg2MjIyMjQ4LCJqdGkiOiIwOWJhOWExYS04NjYyLTQ2NDQtYmE4NC0zMmZiYmI0N2FhMzEifQ.WUNPY--KsX9OvAjj303R7NNt69HEDf1APiZou0mHUMxsTgdnowyKZ8HG2GV_9gbwJ5Os2Btjuj9C0c3ORW2jPd-Z0fJ1B_167Ko84DpqB3a61bo_lyCy4qcZnUsO1j3bMZshhIWdG-mNkW78ie6L3-pAltDPs_TKZR_9DGugoERXptAyHevaKpzc4QOA6ttz5PEsHnOlhLq9HLuAtrF9KSjX6_ZatdkEUrpGVKRsHcBORBsmdTC1U7hGfio0V0ECl6ECnZ2rGFP9a9bA14Ur15uPPxxj2zCll0R2ixU_8TysPovIPewXEijY0Q7f6aDEbpaQUuQo-PshboBFDvlY8g


### Get all notes
GET https://k48o8n9ofl.execute-api.us-east-1.amazonaws.com/dev/notes
Authorization: eyJraWQiOiJrb3RSYU1DRVhBdzhDUENYXC9acE9EcjVnZ3JpXC95ZTlJcnhVNGYzMjl0RDQ9IiwiYWxnIjoiUlMyNTYifQ.eyJvcmlnaW5fanRpIjoiNGZmODFmODgtZjIwYS00M2U3LWIyZDEtODdjODRhYjljYTA4Iiwic3ViIjoiYzRjOTFiMmItMGM4Ni00MGJmLWExZjgtOTI4ZTM0NDdkMjgxIiwiYXVkIjoiNXQwZ2RiaDcycXU1djVsbmdqMGdqZG0zdTUiLCJldmVudF9pZCI6IjgxNTE3YzVlLWRhZDAtNGUyYy1hMWZlLTIwMmFhMmRjOWRhNCIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNjg2MjI2MDMzLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9EVTBvb3lwazIiLCJjb2duaXRvOnVzZXJuYW1lIjoidGVzdCIsImV4cCI6MTY4NjIyOTYzMywiaWF0IjoxNjg2MjI2MDMzLCJqdGkiOiIwZjYxNjk5OC0zYmJmLTQzNmUtOWQ3NS0yY2MwMmU2Y2ZhZjIifQ.A6e1ecQYloCl-pKa8U4k0U1c_vvEp5fTbwIATmumfNxaYlk4rTXV1vgO4yaVxDrY9vhVWndCqhmA8eGxeeKCoHoyVkvYnIUWDsvtI56D80ZRQ6imLKzULlZHG0Yj78oIu_pmOINgHlOM-GzQ4_5qG3QJ_q9OrbHYg6JBn3TOTqkgl6109aTDiskzZY32X8iVyO3MLAujqTPs61yGgfdXiXlDR9oRcROwliz-SHE8OHjQjKFiWK_R1gyp6Gm5_FF2QfxpCP0MadtUVj0nOzA6sUzpdv3MKhZkMOd2Wpa1yot734k0m6OiiV-lNAPkABIXumUjFr5yED0n1yqtRD9Khg