### Create note
POST https://86heudi5f6.execute-api.us-east-1.amazonaws.com/dev/notes
Content-Type: application/json
Authorization: eyJraWQiOiJrb3RSYU1DRVhBdzhDUENYXC9acE9EcjVnZ3JpXC95ZTlJcnhVNGYzMjl0RDQ9IiwiYWxnIjoiUlMyNTYifQ.eyJhdF9oYXNoIjoiQmVfeWtJZWw0Rk44VHlwbXlERWlJUSIsInN1YiI6ImM0YzkxYjJiLTBjODYtNDBiZi1hMWY4LTkyOGUzNDQ3ZDI4MSIsImF1ZCI6IjV0MGdkYmg3MnF1NXY1bG5najBnamRtM3U1IiwiZXZlbnRfaWQiOiI4OTdjZGQ3YS05ODU4LTRmODItOWYxMy05ZjNlNTBkNGYwNzkiLCJ0b2tlbl91c2UiOiJpZCIsImF1dGhfdGltZSI6MTY4NjE3NDgxOCwiaXNzIjoiaHR0cHM6XC9cL2NvZ25pdG8taWRwLnVzLWVhc3QtMS5hbWF6b25hd3MuY29tXC91cy1lYXN0LTFfRFUwb295cGsyIiwiY29nbml0bzp1c2VybmFtZSI6InRlc3QiLCJleHAiOjE2ODYxNzg0MTgsImlhdCI6MTY4NjE3NDgxOCwianRpIjoiYzI2NmVkZDktZjFmMi00Y2EzLWJjNDktY2RiNTViMzI4OTUyIn0.ip2g4vqbBB3ZzXWuAxFkc61JicOy7Tik1qDXb149dabsAteKakSaydIM2zSJHPShIbhzalk3hCUbfvCCSfXtgju5gnqGVxXCYBiaQLOfvaUVR8vpWSIS7dE4uIzTY8F1POffsLB5NsZa84KpU9Lro1d5zomum8VbpYzaUI9jsLsCedxlBuOeYD-nZrF01GQbGZ-f9pXytpFasG92c_DbQXKj8gO3aCICdfeeW4j84EBJG7N-mOpu200d_b-jM2iDf4btKRurw3qaWufM0CcDYac81xKrRTPxUL6PrNJJDRYr5_aKIDxA3UtAz2BjgM1MXI_ipG-PYzVRtWDlyHZW0g

{
    "id": "103",
    "title": "my first note",
    "content": "Hello world!"
}


### Update note
PUT https://86heudi5f6.execute-api.us-east-1.amazonaws.com/dev/notes/1003
Content-Type: application/json
Authorization: eyJraWQiOiJrb3RSYU1DRVhBdzhDUENYXC9acE9EcjVnZ3JpXC95ZTlJcnhVNGYzMjl0RDQ9IiwiYWxnIjoiUlMyNTYifQ.eyJvcmlnaW5fanRpIjoiYWQzMDRkZjMtNjZlZC00ODY5LThiN2EtOTRlNDk2NTMwYmE3Iiwic3ViIjoiYzRjOTFiMmItMGM4Ni00MGJmLWExZjgtOTI4ZTM0NDdkMjgxIiwiYXVkIjoiNXQwZ2RiaDcycXU1djVsbmdqMGdqZG0zdTUiLCJldmVudF9pZCI6IjY3NDRhNjU4LTMwMDEtNDM3MS05Y2RlLTVjNTU0ZGM2YTM0ZSIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNjg2MjIyNDA5LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9EVTBvb3lwazIiLCJjb2duaXRvOnVzZXJuYW1lIjoidGVzdCIsImV4cCI6MTY4NjIyNjAwOSwiaWF0IjoxNjg2MjIyNDA5LCJqdGkiOiI4NzI4ZGYwNS0wYzYwLTQ0MGQtOTVjZS05Y2E3Nzg2MTY1ZjkifQ.DGWg5rfnSWtlGh9_YCsUwPl0vzRpFbU_dtbycy0xqmqh0jc_8d8hCbI4oCrWUKZ9aX5-50bcSNj_HcIZxUj_DBciOZlIHE8tDB6vXQhooXFiqr9_EQSU8g5-zO8oPC6glCz5vhYVCyfjwNZm9ywoBLmrJ7tWQ0442Yo5Kk7btEc7OR9F87Eg034fE963HMP5rRe0laHZqOcQmch4HJ30dJLBvi72sjwIy9bwnYh1WeTnu3KO-KsVe_3nLCrzdwu0ktFsjW1FsbkNfh_m2oN13pvwT-_ZCZ3dmgRUPmiMJXUDPjGkwWN75tzZ3P6ceed2osESxC1oF3IvtIB7TZfn_A

{
    "title": "Update title",
    "content": "Hello again!"
}


### Delete note
DELETE https://86heudi5f6.execute-api.us-east-1.amazonaws.com/dev/notes/1003
Authorization: eyJraWQiOiJrb3RSYU1DRVhBdzhDUENYXC9acE9EcjVnZ3JpXC95ZTlJcnhVNGYzMjl0RDQ9IiwiYWxnIjoiUlMyNTYifQ.eyJvcmlnaW5fanRpIjoiOTUzMTViYTctMWIzMy00NjNmLWFlNWYtMzU4NGI1NGI0MDQ2Iiwic3ViIjoiYzRjOTFiMmItMGM4Ni00MGJmLWExZjgtOTI4ZTM0NDdkMjgxIiwiYXVkIjoiNXQwZ2RiaDcycXU1djVsbmdqMGdqZG0zdTUiLCJldmVudF9pZCI6ImI0YTcyNWRjLTZlODktNDdhNS1iNGNmLWY1NzQ0MzVmODg5NSIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNjg2MjIyMjQ4LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9EVTBvb3lwazIiLCJjb2duaXRvOnVzZXJuYW1lIjoidGVzdCIsImV4cCI6MTY4NjIyNTg0OCwiaWF0IjoxNjg2MjIyMjQ4LCJqdGkiOiIwOWJhOWExYS04NjYyLTQ2NDQtYmE4NC0zMmZiYmI0N2FhMzEifQ.WUNPY--KsX9OvAjj303R7NNt69HEDf1APiZou0mHUMxsTgdnowyKZ8HG2GV_9gbwJ5Os2Btjuj9C0c3ORW2jPd-Z0fJ1B_167Ko84DpqB3a61bo_lyCy4qcZnUsO1j3bMZshhIWdG-mNkW78ie6L3-pAltDPs_TKZR_9DGugoERXptAyHevaKpzc4QOA6ttz5PEsHnOlhLq9HLuAtrF9KSjX6_ZatdkEUrpGVKRsHcBORBsmdTC1U7hGfio0V0ECl6ECnZ2rGFP9a9bA14Ur15uPPxxj2zCll0R2ixU_8TysPovIPewXEijY0Q7f6aDEbpaQUuQo-PshboBFDvlY8g


### Get all notes
GET https://86heudi5f6.execute-api.us-east-1.amazonaws.com/dev/notes
Authorization: eyJraWQiOiJrb3RSYU1DRVhBdzhDUENYXC9acE9EcjVnZ3JpXC95ZTlJcnhVNGYzMjl0RDQ9IiwiYWxnIjoiUlMyNTYifQ.eyJvcmlnaW5fanRpIjoiYWQzMDRkZjMtNjZlZC00ODY5LThiN2EtOTRlNDk2NTMwYmE3Iiwic3ViIjoiYzRjOTFiMmItMGM4Ni00MGJmLWExZjgtOTI4ZTM0NDdkMjgxIiwiYXVkIjoiNXQwZ2RiaDcycXU1djVsbmdqMGdqZG0zdTUiLCJldmVudF9pZCI6IjY3NDRhNjU4LTMwMDEtNDM3MS05Y2RlLTVjNTU0ZGM2YTM0ZSIsInRva2VuX3VzZSI6ImlkIiwiYXV0aF90aW1lIjoxNjg2MjIyNDA5LCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAudXMtZWFzdC0xLmFtYXpvbmF3cy5jb21cL3VzLWVhc3QtMV9EVTBvb3lwazIiLCJjb2duaXRvOnVzZXJuYW1lIjoidGVzdCIsImV4cCI6MTY4NjIyNjAwOSwiaWF0IjoxNjg2MjIyNDA5LCJqdGkiOiI4NzI4ZGYwNS0wYzYwLTQ0MGQtOTVjZS05Y2E3Nzg2MTY1ZjkifQ.DGWg5rfnSWtlGh9_YCsUwPl0vzRpFbU_dtbycy0xqmqh0jc_8d8hCbI4oCrWUKZ9aX5-50bcSNj_HcIZxUj_DBciOZlIHE8tDB6vXQhooXFiqr9_EQSU8g5-zO8oPC6glCz5vhYVCyfjwNZm9ywoBLmrJ7tWQ0442Yo5Kk7btEc7OR9F87Eg034fE963HMP5rRe0laHZqOcQmch4HJ30dJLBvi72sjwIy9bwnYh1WeTnu3KO-KsVe_3nLCrzdwu0ktFsjW1FsbkNfh_m2oN13pvwT-_ZCZ3dmgRUPmiMJXUDPjGkwWN75tzZ3P6ceed2osESxC1oF3IvtIB7TZfn_A