# Notes dynamodb table
notesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: notes
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: notesId
        AttributeType: S
    KeySchema:
      - AttributeName: notesId
        KeyType: HASH

# Cognito user pool
cognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: MyNoteUserPool

# User pool web client
cognitoUserPoolWebClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    UserPoolId: !Ref cognitoUserPool
    ClientName: web
    AllowedOAuthFlows:
      - implicit
    CallbackURLs:
      - http://localhost:3000
    SupportedIdentityProviders:
      - COGNITO
    AllowedOAuthFlowsUserPoolClient: true
    AllowedOAuthScopes:
      - phone
      - email
      - profile
      - openid

# Cognito pool domain
userPoolDomain:
  Type: AWS::Cognito::UserPoolDomain
  Properties:
    Domain: mynotecd
    UserPoolId: !Ref cognitoUserPool
